#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/functions/mulle-sprintf-character.c
src/functions/mulle-sprintf-escape.c
src/functions/mulle-sprintf-fp.c
src/functions/mulle-sprintf-integer.c
src/functions/mulle-sprintf-pointer.c
src/functions/mulle-sprintf-return.c
src/functions/mulle-sprintf-string.c
src/mulle-sprintf.c
src/mulle-sprintf-function.c
)

set( STANDALONE_SOURCES
src/mulle-sprintf-standalone.c
)
