# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/functions/mulle-sprintf-character.c
src/functions/mulle-sprintf-escape.c
src/functions/mulle-sprintf-fp.c
src/functions/mulle-sprintf-integer.c
src/functions/mulle-sprintf-pointer.c
src/functions/mulle-sprintf-return.c
src/functions/mulle-sprintf-string.c
src/mulle-dtoa/mulle-dtoa.c
src/mulle-sprintf.c
src/mulle-sprintf-function.c
)

#
# contents selected with patternfile ??-source--standalone-sources
#
set( STANDALONE_SOURCES
src/mulle-sprintf-standalone.c
)
