/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_sprintf_include_h__
#define _mulle_sprintf_include_h__

// How to tweak the following mulle-buffer #include
//    remove:          `mulle-sourcetree mark mulle-buffer no-header`
//    rename:          `mulle-sourcetree mark mulle-buffer set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark mulle-buffer [no-]import`
//    toggle public:   `mulle-sourcetree mark mulle-buffer [no-]public`
//    toggle optional: `mulle-sourcetree mark mulle-buffer [no-]require`
//    remove for os:   `mulle-sourcetree mark mulle-buffer no-os-<osname>`
# include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

// How to tweak the following mulle-utf #include
//    remove:          `mulle-sourcetree mark mulle-utf no-header`
//    rename:          `mulle-sourcetree mark mulle-utf set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark mulle-utf [no-]import`
//    toggle public:   `mulle-sourcetree mark mulle-utf [no-]public`
//    toggle optional: `mulle-sourcetree mark mulle-utf [no-]require`
//    remove for os:   `mulle-sourcetree mark mulle-utf no-os-<osname>`
# include <mulle-utf/mulle-utf.h>   // mulle-utf

// How to tweak the following mulle-vararg #include
//    remove:          `mulle-sourcetree mark mulle-vararg no-header`
//    rename:          `mulle-sourcetree mark mulle-vararg set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark mulle-vararg [no-]import`
//    toggle public:   `mulle-sourcetree mark mulle-vararg [no-]public`
//    toggle optional: `mulle-sourcetree mark mulle-vararg [no-]require`
//    remove for os:   `mulle-sourcetree mark mulle-vararg no-os-<osname>`
# include <mulle-vararg/mulle-vararg.h>   // mulle-vararg

// How to tweak the following mulle-thread #include
//    remove:          `mulle-sourcetree mark mulle-thread no-header`
//    rename:          `mulle-sourcetree mark mulle-thread set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark mulle-thread [no-]import`
//    toggle public:   `mulle-sourcetree mark mulle-thread [no-]public`
//    toggle optional: `mulle-sourcetree mark mulle-thread [no-]require`
//    remove for os:   `mulle-sourcetree mark mulle-thread no-os-<osname>`
# include <mulle-thread/mulle-thread.h>   // mulle-thread

#endif
