/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE__BUFFER_VERSION)
# if MULLE__BUFFER_VERSION < ((3 << 20) | (4 << 8) | 0)
#  error "mulle-buffer is too old"
# endif
# if MULLE__BUFFER_VERSION >= ((4 << 20) | (0 << 8) | 0)
#  error "mulle-buffer is too new"
# endif
#endif

#if defined( MULLE__THREAD_VERSION)
# if MULLE__THREAD_VERSION < ((4 << 20) | (5 << 8) | 1)
#  error "mulle-thread is too old"
# endif
# if MULLE__THREAD_VERSION >= ((5 << 20) | (0 << 8) | 0)
#  error "mulle-thread is too new"
# endif
#endif

#if defined( MULLE__UTF_VERSION)
# if MULLE__UTF_VERSION < ((3 << 20) | (1 << 8) | 3)
#  error "mulle-utf is too old"
# endif
# if MULLE__UTF_VERSION >= ((4 << 20) | (0 << 8) | 0)
#  error "mulle-utf is too new"
# endif
#endif

#if defined( MULLE__VARARG_VERSION)
# if MULLE__VARARG_VERSION < ((1 << 20) | (1 << 8) | 5)
#  error "mulle-vararg is too old"
# endif
# if MULLE__VARARG_VERSION >= ((2 << 20) | (0 << 8) | 0)
#  error "mulle-vararg is too new"
# endif
#endif
