/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_sprintf_versioncheck_h__
#define mulle_sprintf_versioncheck_h__

#if defined( MULLE__BUFFER_VERSION)
# ifndef MULLE__BUFFER_VERSION_MIN
#  define MULLE__BUFFER_VERSION_MIN  ((3 << 20) | (5 << 8) | 0)
# endif
# ifndef MULLE__BUFFER_VERSION_MAX
#  define MULLE__BUFFER_VERSION_MAX  ((4 << 20) | (0 << 8) | 0)
# endif
# if MULLE__BUFFER_VERSION < MULLE__BUFFER_VERSION_MIN
#  error "mulle-buffer is too old"
# endif
# if MULLE__BUFFER_VERSION >= MULLE__BUFFER_VERSION_MAX
#  error "mulle-buffer is too new"
# endif
#endif

#if defined( MULLE__THREAD_VERSION)
# ifndef MULLE__THREAD_VERSION_MIN
#  define MULLE__THREAD_VERSION_MIN  ((4 << 20) | (5 << 8) | 2)
# endif
# ifndef MULLE__THREAD_VERSION_MAX
#  define MULLE__THREAD_VERSION_MAX  ((5 << 20) | (0 << 8) | 0)
# endif
# if MULLE__THREAD_VERSION < MULLE__THREAD_VERSION_MIN
#  error "mulle-thread is too old"
# endif
# if MULLE__THREAD_VERSION >= MULLE__THREAD_VERSION_MAX
#  error "mulle-thread is too new"
# endif
#endif

#if defined( MULLE__UTF_VERSION)
# ifndef MULLE__UTF_VERSION_MIN
#  define MULLE__UTF_VERSION_MIN  ((4 << 20) | (0 << 8) | 0)
# endif
# ifndef MULLE__UTF_VERSION_MAX
#  define MULLE__UTF_VERSION_MAX  ((5 << 20) | (0 << 8) | 0)
# endif
# if MULLE__UTF_VERSION < MULLE__UTF_VERSION_MIN
#  error "mulle-utf is too old"
# endif
# if MULLE__UTF_VERSION >= MULLE__UTF_VERSION_MAX
#  error "mulle-utf is too new"
# endif
#endif

#if defined( MULLE__VARARG_VERSION)
# ifndef MULLE__VARARG_VERSION_MIN
#  define MULLE__VARARG_VERSION_MIN  ((1 << 20) | (1 << 8) | 6)
# endif
# ifndef MULLE__VARARG_VERSION_MAX
#  define MULLE__VARARG_VERSION_MAX  ((2 << 20) | (0 << 8) | 0)
# endif
# if MULLE__VARARG_VERSION < MULLE__VARARG_VERSION_MIN
#  error "mulle-vararg is too old"
# endif
# if MULLE__VARARG_VERSION >= MULLE__VARARG_VERSION_MAX
#  error "mulle-vararg is too new"
# endif
#endif

#endif
