/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_INCLUDE_FILE NONE|DISABLE.
*/
/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_INCLUDE_FILE NONE|DISABLE.
*/

#ifndef _mulle_sprintf_include_h__
#define _mulle_sprintf_include_h__

# include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

# include <mulle-utf/mulle-utf.h>   // mulle-utf

# include <mulle-vararg/mulle-vararg.h>   // mulle-vararg

# include <mulle-thread/mulle-thread.h>   // mulle-thread

#endif

