/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_sprintf__dependencies_h__
#define _mulle_sprintf__dependencies_h__

# include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

# include <mulle-utf/mulle-utf.h>   // mulle-utf

# include <mulle-vararg/mulle-vararg.h>   // mulle-vararg

#endif
