/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*/

#ifndef _mulle_sprintf_include_h__
#define _mulle_sprintf_include_h__

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-utf/mulle-utf.h>   // mulle-utf

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-vararg/mulle-vararg.h>   // mulle-vararg

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-thread/mulle-thread.h>   // mulle-thread

#endif
